export type ProductCategory =
  | "alabaster"
  | "marble"
  | "mosaic"
  | "sparkle"
  | "translucent"
  | "plain"

export type Industry =
  | "residential"
  | "commercial"
  | "healthcare"
  | "corporate"
  | "hospitality"

export type Product = {
  slug: string
  name: string
  sku: string
  category: ProductCategory
  description: string
  longDescription: string
  image: string
  gallery: string[]
  hue: string
  region: string
  isNew?: boolean
  isEco?: boolean
  thickness: string
  dimensions: string
  applications: string[]
  features: string[]
  industries: Industry[]
  videoUrl?: string
  specSheetUrl?: string
  faqs?: { q: string; a: string }[]
}

export const categories: { id: ProductCategory | "all"; label: string }[] = [
  { id: "all", label: "All" },
  { id: "alabaster", label: "Alabaster" },
  { id: "marble", label: "Marble" },
  { id: "mosaic", label: "Mosaic" },
  { id: "sparkle", label: "Sparkle" },
  { id: "translucent", label: "Translucent" },
  { id: "plain", label: "Plain Surface" },
]

export const industries: { id: Industry | "all"; label: string }[] = [
  { id: "all", label: "All Industries" },
  { id: "residential", label: "Residential" },
  { id: "commercial", label: "Commercial" },
  { id: "healthcare", label: "Healthcare" },
  { id: "corporate", label: "Corporate" },
  { id: "hospitality", label: "Hospitality" },
]

const defaultFaqs = [
  {
    q: "Is this surface suitable for kitchen countertops?",
    a: "Yes. All Flexicore solid surfaces are non-porous, food-safe, and NSF-certified for kitchen use. They resist staining, bacteria, and heat up to 180 degrees Celsius with a trivet.",
  },
  {
    q: "How do I maintain and clean the surface?",
    a: "Daily cleaning requires only warm water and mild soap. For deeper cleans use a non-abrasive cream cleanser. Scratches and minor scuffs can be buffed out with a fine abrasive pad, restoring the surface to like-new condition.",
  },
  {
    q: "What warranty does Flexicore offer?",
    a: "Every Flexicore installation comes with a 10-year limited residential warranty covering material defects and workmanship performed by certified Flexicore fabricators.",
  },
]

export const products: Product[] = [
  {
    slug: "white-fantacy",
    name: "White Fantacy",
    sku: "FC-401",
    category: "marble",
    description: "Elegant white surface with subtle fantasy patterns.",
    longDescription: "White Fantacy features a crisp white base with delicate fantasy-inspired patterns for a modern, airy look.",
    image: "/products/marble/fc-401.png",
    gallery: ["/products/marble/fc-401.png"],
    hue: "White",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Countertop", "Vanity", "Feature Wall"],
    features: ["Non-porous", "Stain resistant", "Thermoformable"],
    industries: ["residential", "hospitality", "commercial"],
    faqs: defaultFaqs,
  },
  {
    slug: "stonewood",
    name: "Stonewood",
    sku: "FC-402",
    category: "marble",
    description: "Warm stone surface with wood-like grain textures.",
    longDescription: "Stonewood combines the durability of stone with the warm, organic feel of wood grain patterns.",
    image: "/products/marble/fc-402.png",
    gallery: ["/products/marble/fc-402.png"],
    hue: "Beige",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Kitchen", "Bathroom", "Furniture"],
    features: ["Non-porous", "Hygienic", "Seamless joints"],
    industries: ["residential", "hospitality", "commercial"],
    faqs: defaultFaqs,
  },
  {
    slug: "black-fantasy",
    name: "Black Fantasy",
    sku: "FC-403",
    category: "marble",
    description: "Deep black with mesmerizing fantasy veining.",
    longDescription: "Black Fantasy delivers a bold, sophisticated look with deep black tones and intricate veining.",
    image: "/products/marble/fc-403.png",
    gallery: ["/products/marble/fc-403.png"],
    hue: "Black",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Bar Top", "Reception", "Feature Wall"],
    features: ["Non-porous", "Stain resistant", "Anti-bacterial"],
    industries: ["commercial", "hospitality", "corporate"],
    faqs: defaultFaqs,
  },
  {
    slug: "brown-fantacy",
    name: "Brown Fantacy",
    sku: "FC-404",
    category: "marble",
    description: "Rich brown base with elegant fantasy patterns.",
    longDescription: "Brown Fantacy offers warm earthy tones with elegant patterns, perfect for creating cozy yet luxurious spaces.",
    image: "/products/marble/fc-404.png",
    gallery: ["/products/marble/fc-404.png"],
    hue: "Beige",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Countertop", "Vanity", "Retail"],
    features: ["Warm tone", "Hygienic", "Thermoformable"],
    industries: ["residential", "hospitality", "commercial"],
    faqs: defaultFaqs,
  },
  {
    slug: "pietra-grey",
    name: "Pietra Grey",
    sku: "FC-405",
    category: "marble",
    description: "Classic grey marble with white linear veining.",
    longDescription: "Pietra Grey captures the timeless elegance of classic grey marble with refined white veining.",
    image: "/products/marble/fc-405.png",
    gallery: ["/products/marble/fc-405.png"],
    hue: "Black",
    region: "Europe",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Kitchen", "Bathroom", "Flooring"],
    features: ["Non-porous", "Seamless", "Stain resistant"],
    industries: ["residential", "hospitality", "commercial"],
    faqs: defaultFaqs,
  },
  {
    slug: "carrara-white-marble",
    name: "Carrara White Marble",
    sku: "FC-406",
    category: "marble",
    description: "Iconic white marble look with soft grey veining.",
    longDescription: "Carrara White Marble brings the classic luxury of Italian Carrara marble to high-performance solid surfaces.",
    image: "/products/marble/fc-406.png",
    gallery: ["/products/marble/fc-406.png"],
    hue: "White",
    region: "Europe",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Vanity", "Kitchen", "Lobby"],
    features: ["Non-porous", "Hygienic", "Seamless"],
    industries: ["residential", "hospitality", "healthcare"],
    faqs: defaultFaqs,
  },
  {
    slug: "moonstone-flow",
    name: "Moonstone Flow",
    sku: "FC-407",
    category: "marble",
    description: "Ethereal moonstone surface with flowing patterns.",
    longDescription: "Moonstone Flow features ethereal tones and gentle flowing patterns, evoking the calm beauty of moonlit stone.",
    image: "/products/marble/fc-407.png",
    gallery: ["/products/marble/fc-407.png"],
    hue: "White",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Spa", "Bathroom", "Feature Wall"],
    features: ["Non-porous", "Thermoformable", "Seamless"],
    industries: ["hospitality", "residential", "healthcare"],
    faqs: defaultFaqs,
  },
  {
    slug: "graphite-vein",
    name: "Graphite Vein",
    sku: "FC-408",
    category: "marble",
    description: "Crisp surface with sharp graphite-colored veins.",
    longDescription: "Graphite Vein offers a striking contrast with sharp graphite veins over a clean base for a modern look.",
    image: "/products/marble/fc-408.png",
    gallery: ["/products/marble/fc-408.png"],
    hue: "White",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Countertop", "Reception Desk", "Retail"],
    features: ["Non-porous", "Stain resistant", "Repairable"],
    industries: ["commercial", "corporate", "hospitality"],
    faqs: defaultFaqs,
  },
  {
    slug: "mist-aura-marble",
    name: "Mist Aura Marble",
    sku: "FC-409",
    category: "marble",
    description: "Soft mist patterns with a luxurious marble aura.",
    longDescription: "Mist Aura Marble features soft misty patterns and a luxurious marble-inspired aura for elegant spaces.",
    image: "/products/marble/fc-409.png",
    gallery: ["/products/marble/fc-409.png"],
    hue: "White",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Kitchen", "Bathroom", "Hospitality"],
    features: ["Non-porous", "Hygienic", "Seamless"],
    industries: ["residential", "hospitality", "healthcare"],
    faqs: defaultFaqs,
  },
  {
    slug: "blush-marble-white",
    name: "Blush Marble White",
    sku: "FC-410",
    category: "marble",
    description: "White marble base with subtle blush undertones.",
    longDescription: "Blush Marble White offers a unique twist on classic marble with subtle blush undertones for a warm, sophisticated finish.",
    image: "/products/marble/fc-410.png",
    gallery: ["/products/marble/fc-410.png"],
    hue: "White",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Vanity", "Feature Wall", "Residential"],
    features: ["Non-porous", "Stain resistant", "Thermoformable"],
    industries: ["residential", "hospitality", "commercial"],
    faqs: defaultFaqs,
  },
  {
    slug: "noir-obsidian",
    name: "Noir Obsidian",
    sku: "FC-PL-202",
    category: "plain",
    description: "A deep, velvety black with a soft matte finish.",
    longDescription:
      "Noir Obsidian delivers an ultra-deep black with a velvety matte finish, perfect for modern architectural statements and minimalist luxury interiors.",
    image: "https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=1600&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1600&q=80",
    ],
    hue: "Black",
    region: "Global",
    isNew: true,
    isEco: true,
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Reception Desk", "Countertop", "Bar Top"],
    features: ["Non-porous", "Anti-bacterial", "Repairable", "Recycled content"],
    industries: ["corporate", "hospitality", "commercial"],
    videoUrl: "https://cdn.coverr.co/videos/coverr-modern-black-kitchen-8124/1080p.mp4",
    specSheetUrl: "/specs/noir-obsidian.pdf",
    faqs: defaultFaqs,
  },
  {
    slug: "ivory-mist-strands",
    name: "Ivory Mist Strands",
    sku: "FC-701",
    category: "alabaster",
    description: "Elegant ivory surface with soft misty strand patterns.",
    longDescription: "Ivory Mist Strands features delicate, flowing strand patterns over an ivory base, evoking the timeless beauty of natural alabaster stone.",
    image: "/products/alabaster/fc-701.png",
    gallery: ["/products/alabaster/fc-701.png"],
    hue: "White",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Countertop", "Feature Wall", "Vanity"],
    features: ["Non-porous", "Stain resistant", "Thermoformable"],
    industries: ["residential", "hospitality", "commercial"],
    faqs: defaultFaqs,
  },
  {
    slug: "honey-marble-lines",
    name: "Honey Marble Lines",
    sku: "FC-702",
    category: "alabaster",
    description: "Warm honey tones with flowing marble line patterns.",
    longDescription: "Honey Marble Lines combines warm honey tones with flowing marble-inspired veining for a rich, natural look.",
    image: "/products/alabaster/fc-702.png",
    gallery: ["/products/alabaster/fc-702.png"],
    hue: "Beige",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Kitchen", "Bathroom", "Lobby"],
    features: ["Non-porous", "Seamless joints", "Hygienic"],
    industries: ["residential", "hospitality", "commercial"],
    faqs: defaultFaqs,
  },
  {
    slug: "royal-pearl-drift",
    name: "Royal Pearl Drift",
    sku: "FC-703",
    category: "alabaster",
    description: "Pearlescent surface with royal drift patterns.",
    longDescription: "Royal Pearl Drift showcases a pearlescent base with soft drifting veins, perfect for elegant interiors.",
    image: "/products/alabaster/fc-703.png",
    gallery: ["/products/alabaster/fc-703.png"],
    hue: "White",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Vanity", "Feature Wall", "Reception"],
    features: ["Non-porous", "Stain resistant", "Thermoformable"],
    industries: ["residential", "hospitality", "commercial"],
    faqs: defaultFaqs,
  },
  {
    slug: "desert-sand-stripes",
    name: "Desert Sand Stripes",
    sku: "FC-704",
    category: "alabaster",
    description: "Sandy tones with natural stripe formations.",
    longDescription: "Desert Sand Stripes brings the warmth of desert landscapes with elegant stripe patterns across a sandy base.",
    image: "/products/alabaster/fc-704.png",
    gallery: ["/products/alabaster/fc-704.png"],
    hue: "Beige",
    region: "Middle East",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Countertop", "Hospitality", "Retail"],
    features: ["Warm tone", "Hygienic", "Thermoformable"],
    industries: ["hospitality", "commercial", "residential"],
    faqs: defaultFaqs,
  },
  {
    slug: "golden-ember-mix",
    name: "Golden Ember Mix",
    sku: "FC-705",
    category: "alabaster",
    description: "Rich golden tones with ember-like mixed patterns.",
    longDescription: "Golden Ember Mix features rich golden hues with ember-inspired mixed patterns for a warm, luxurious finish.",
    image: "/products/alabaster/fc-705.png",
    gallery: ["/products/alabaster/fc-705.png"],
    hue: "Beige",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Feature Wall", "Bar Top", "Reception"],
    features: ["Non-porous", "Seamless", "Thermoformable"],
    industries: ["hospitality", "commercial", "corporate"],
    faqs: defaultFaqs,
  },
  {
    slug: "caramel-smoke-lines",
    name: "Caramel Smoke Lines",
    sku: "FC-706",
    category: "alabaster",
    description: "Caramel base with smoky line detailing.",
    longDescription: "Caramel Smoke Lines offers a caramel-toned base with smoky line detailing for a contemporary natural look.",
    image: "/products/alabaster/fc-706.png",
    gallery: ["/products/alabaster/fc-706.png"],
    hue: "Beige",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Kitchen", "Bathroom", "Commercial"],
    features: ["Non-porous", "Stain resistant", "Repairable"],
    industries: ["residential", "commercial", "hospitality"],
    faqs: defaultFaqs,
  },
  {
    slug: "fresh-moss-lines",
    name: "Fresh Moss Lines",
    sku: "FC-707",
    category: "alabaster",
    description: "Fresh green moss-inspired line patterns.",
    longDescription: "Fresh Moss Lines brings nature indoors with fresh green moss-inspired line patterns over a soft base.",
    image: "/products/alabaster/fc-707.png",
    gallery: ["/products/alabaster/fc-707.png"],
    hue: "Green",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Spa", "Hospitality", "Retail"],
    features: ["Non-porous", "Hygienic", "Thermoformable"],
    industries: ["hospitality", "residential", "healthcare"],
    faqs: defaultFaqs,
  },
  {
    slug: "natural-grain-marble",
    name: "Natural Grain Marble",
    sku: "FC-708",
    category: "alabaster",
    description: "Natural grain patterns with marble aesthetics.",
    longDescription: "Natural Grain Marble combines natural grain textures with marble-inspired aesthetics for a timeless surface.",
    image: "/products/alabaster/fc-708.png",
    gallery: ["/products/alabaster/fc-708.png"],
    hue: "Beige",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Countertop", "Vanity", "Flooring"],
    features: ["Non-porous", "Seamless joints", "Stain resistant"],
    industries: ["residential", "hospitality", "commercial"],
    faqs: defaultFaqs,
  },
  {
    slug: "golden-aura-swirl",
    name: "Golden Aura Swirl",
    sku: "FC-709",
    category: "alabaster",
    description: "Swirling golden aura patterns on a warm base.",
    longDescription: "Golden Aura Swirl features mesmerizing swirl patterns with golden aura tones, adding luxury to any space.",
    image: "/products/alabaster/fc-709.png",
    gallery: ["/products/alabaster/fc-709.png"],
    hue: "Beige",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Feature Wall", "Reception", "Bar"],
    features: ["Non-porous", "Thermoformable", "Seamless"],
    industries: ["hospitality", "commercial", "corporate"],
    faqs: defaultFaqs,
  },
  {
    slug: "inferno-marble",
    name: "Inferno Marble",
    sku: "FC-710",
    category: "alabaster",
    description: "Bold inferno-inspired marble patterns.",
    longDescription: "Inferno Marble delivers bold, fiery marble patterns for dramatic statement surfaces in modern interiors.",
    image: "/products/alabaster/fc-710.png",
    gallery: ["/products/alabaster/fc-710.png"],
    hue: "Orange",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Feature Wall", "Bar Top", "Reception"],
    features: ["Non-porous", "Stain resistant", "Thermoformable"],
    industries: ["hospitality", "commercial", "corporate"],
    faqs: defaultFaqs,
  },
  {
    slug: "rustwood-grain",
    name: "Rustwood Grain",
    sku: "FC-711",
    category: "alabaster",
    description: "Rustic wood grain inspired surface.",
    longDescription: "Rustwood Grain captures the warmth of rustic wood grain in a durable, non-porous solid surface.",
    image: "/products/alabaster/fc-711.png",
    gallery: ["/products/alabaster/fc-711.png"],
    hue: "Beige",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Kitchen", "Furniture", "Commercial"],
    features: ["Non-porous", "Hygienic", "Repairable"],
    industries: ["residential", "commercial", "hospitality"],
    faqs: defaultFaqs,
  },
  {
    slug: "cream-mist-marble",
    name: "Cream Mist Marble",
    sku: "FC-712",
    category: "alabaster",
    description: "Creamy mist with soft marble veining.",
    longDescription: "Cream Mist Marble features a creamy base with soft misty marble veining for a calming, elegant finish.",
    image: "/products/alabaster/fc-712.png",
    gallery: ["/products/alabaster/fc-712.png"],
    hue: "White",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Bathroom", "Kitchen", "Healthcare"],
    features: ["Non-porous", "Hygienic", "Seamless"],
    industries: ["residential", "healthcare", "hospitality"],
    faqs: defaultFaqs,
  },
  {
    slug: "silver-rose-drift",
    name: "Silver Rose Drift",
    sku: "FC-713",
    category: "alabaster",
    description: "Silver and rose tones with drift patterns.",
    longDescription: "Silver Rose Drift combines silver and rose tones with gentle drift patterns for a sophisticated look.",
    image: "/products/alabaster/fc-713.png",
    gallery: ["/products/alabaster/fc-713.png"],
    hue: "Burgundy",
    region: "Europe",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Retail", "Hospitality", "Vanity"],
    features: ["Non-porous", "Thermoformable", "Seamless"],
    industries: ["hospitality", "commercial", "residential"],
    faqs: defaultFaqs,
  },
  {
    slug: "sunny-mist-flow",
    name: "Sunny Mist Flow",
    sku: "FC-714",
    category: "alabaster",
    description: "Sunny tones with flowing mist patterns.",
    longDescription: "Sunny Mist Flow brings warm sunny tones with flowing mist-inspired patterns for bright, inviting spaces.",
    image: "/products/alabaster/fc-714.png",
    gallery: ["/products/alabaster/fc-714.png"],
    hue: "Beige",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Kitchen", "Hospitality", "Retail"],
    features: ["Non-porous", "Stain resistant", "Hygienic"],
    industries: ["residential", "hospitality", "commercial"],
    faqs: defaultFaqs,
  },

  {
    slug: "ivory-linen",
    name: "Ivory Linen",
    sku: "FC-PL-105",
    category: "plain",
    description: "Clean ivory with a subtle linen texture.",
    longDescription:
      "Ivory Linen is a soft ivory solid surface with a gentle linen-inspired texture, ideal for calming, light-filled interiors.",
    image: "https://images.unsplash.com/photo-1545239351-1141bd82e8a6?auto=format&fit=crop&w=1600&q=80",
    gallery: ["https://images.unsplash.com/photo-1545239351-1141bd82e8a6?auto=format&fit=crop&w=1600&q=80"],
    hue: "White",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Hospitality", "Healthcare", "Residential"],
    features: ["Hygienic", "Low maintenance"],
    industries: ["healthcare", "hospitality", "residential"],
    specSheetUrl: "/specs/ivory-linen.pdf",
    faqs: defaultFaqs,
  },
  {
    slug: "night-black",
    name: "Night Black",
    sku: "FC-501",
    category: "sparkle",
    description: "Deep night black with subtle shimmering sparkles.",
    longDescription: "Night Black features a deep, dark base with subtle shimmering flecks that evoke a starry night sky.",
    image: "/products/sparkle/fc-501.png",
    gallery: ["/products/sparkle/fc-501.png"],
    hue: "Black",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Reception", "Bar Top", "Feature Wall"],
    features: ["Non-porous", "Light-reactive", "Stain resistant"],
    industries: ["commercial", "hospitality", "corporate"],
    faqs: defaultFaqs,
  },
  {
    slug: "sparkle-white",
    name: "Sparkle White",
    sku: "FC-502",
    category: "sparkle",
    description: "Crisp white with elegant sparkling accents.",
    longDescription: "Sparkle White combines a clean, crisp white base with elegant sparkling accents for a bright, luxurious finish.",
    image: "/products/sparkle/fc-502.png",
    gallery: ["/products/sparkle/fc-502.png"],
    hue: "White",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Kitchen Countertop", "Vanity", "Lobby"],
    features: ["Non-porous", "Hygienic", "Seamless joints"],
    industries: ["residential", "hospitality", "healthcare"],
    faqs: defaultFaqs,
  },
  {
    slug: "cloud-white-translucent",
    name: "Cloud White",
    sku: "FC-201",
    category: "translucent",
    description: "Soft cloud white with elegant translucency.",
    longDescription: "Cloud White offers a soft, ethereal appearance with elegant translucency, perfect for backlit applications and modern interiors.",
    image: "/products/translucent/fc-201.png",
    gallery: ["/products/translucent/fc-201.png"],
    hue: "White",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Backlit Wall", "Vanity", "Reception Desk"],
    features: ["Translucent", "Non-porous", "Seamless joints"],
    industries: ["hospitality", "residential", "corporate"],
    faqs: defaultFaqs,
  },
  {
    slug: "rose-pink",
    name: "Rose Pink",
    sku: "FC-202",
    category: "translucent",
    description: "Gentle rose pink with a glowing translucent finish.",
    longDescription: "Rose Pink brings a gentle, warm glow to any space with its beautiful translucent finish and soft floral tones.",
    image: "/products/translucent/fc-202.png",
    gallery: ["/products/translucent/fc-202.png"],
    hue: "Burgundy",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Feature Wall", "Spa", "Retail"],
    features: ["Translucent", "Stain resistant", "Thermoformable"],
    industries: ["hospitality", "residential", "commercial"],
    faqs: defaultFaqs,
  },
  {
    slug: "mint-green",
    name: "Mint Green",
    sku: "FC-203",
    category: "translucent",
    description: "Fresh mint green with light-transmitting properties.",
    longDescription: "Mint Green offers a fresh, vibrant look with excellent light-transmitting properties, ideal for contemporary design statements.",
    image: "/products/translucent/fc-203.png",
    gallery: ["/products/translucent/fc-203.png"],
    hue: "Green",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Reception", "Bar", "Healthcare"],
    features: ["Translucent", "Hygienic", "Easy to clean"],
    industries: ["commercial", "healthcare", "hospitality"],
    faqs: defaultFaqs,
  },
  {
    slug: "sky-blue",
    name: "Sky Blue",
    sku: "FC-204",
    category: "translucent",
    description: "Serene sky blue with a soft translucent glow.",
    longDescription: "Sky Blue captures the serenity of the open sky with a soft, translucent glow that transforms when backlit.",
    image: "/products/translucent/fc-204.png",
    gallery: ["/products/translucent/fc-204.png"],
    hue: "Blue",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Pool", "Spa", "Bathroom"],
    features: ["Translucent", "Waterproof", "Seamless"],
    industries: ["hospitality", "residential", "healthcare"],
    faqs: defaultFaqs,
  },
  {
    slug: "orange-translucent",
    name: "Orange",
    sku: "FC-205",
    category: "translucent",
    description: "Vibrant orange with high-impact translucency.",
    longDescription: "Orange Translucent delivers a high-impact, vibrant look with exceptional light diffusion for dramatic interiors.",
    image: "/products/translucent/fc-205.png",
    gallery: ["/products/translucent/fc-205.png"],
    hue: "Orange",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Bar Top", "Feature Wall", "Retail"],
    features: ["Translucent", "Stain resistant", "Thermoformable"],
    industries: ["hospitality", "commercial", "corporate"],
    faqs: defaultFaqs,
  },
  {
    slug: "yellow-translucent",
    name: "Yellow",
    sku: "FC-206",
    category: "translucent",
    description: "Bright yellow with luminous light transmission.",
    longDescription: "Yellow Translucent brings a bright, sunny energy to spaces with its luminous light-transmitting capabilities.",
    image: "/products/translucent/fc-206.png",
    gallery: ["/products/translucent/fc-206.png"],
    hue: "Beige",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Reception", "Display", "Feature Wall"],
    features: ["Translucent", "Non-porous", "Hygienic"],
    industries: ["commercial", "hospitality", "retail"],
    faqs: defaultFaqs,
  },
  {
    slug: "silver-fog",
    name: "Silver Fog",
    sku: "FC-207",
    category: "translucent",
    description: "Sophisticated silver fog with a translucent depth.",
    longDescription: "Silver Fog offers a sophisticated, muted look with a unique translucent depth that adds a layer of modern luxury.",
    image: "/products/translucent/fc-207.png",
    gallery: ["/products/translucent/fc-207.png"],
    hue: "White",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Office", "Lobby", "Furniture"],
    features: ["Translucent", "Repairable", "Seamless joints"],
    industries: ["corporate", "commercial", "hospitality"],
    faqs: defaultFaqs,
  },
  {
    slug: "dewy-green",
    name: "Dewy Green",
    sku: "FC-208",
    category: "translucent",
    description: "Natural dewy green with a soft glowing effect.",
    longDescription: "Dewy Green captures the essence of morning dew on leaves with a soft, glowing translucent effect for tranquil spaces.",
    image: "/products/translucent/fc-208.png",
    gallery: ["/products/translucent/fc-208.png"],
    hue: "Green",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Spa", "Bathroom", "Healthcare"],
    features: ["Translucent", "Anti-bacterial", "Non-porous"],
    industries: ["healthcare", "hospitality", "residential"],
    faqs: defaultFaqs,
  },
  {
    slug: "royal-raspberry",
    name: "Royal Raspberry",
    sku: "FC-209",
    category: "translucent",
    description: "Rich royal raspberry with a deep translucent glow.",
    longDescription: "Royal Raspberry features a rich, deep hue with a mesmerizing translucent glow, perfect for luxury statement pieces.",
    image: "/products/translucent/fc-209.png",
    gallery: ["/products/translucent/fc-209.png"],
    hue: "Burgundy",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Bar", "Feature Wall", "Furniture"],
    features: ["Translucent", "Stain resistant", "Seamless"],
    industries: ["hospitality", "commercial", "residential"],
    faqs: defaultFaqs,
  },
  {
    slug: "pebblon-lvory",
    name: "Pebblon Lvory",
    sku: "FC-301",
    category: "mosaic",
    description: "Elegant ivory pebble-inspired mosaic pattern.",
    longDescription: "Pebblon Lvory features an elegant ivory base with pebble-inspired textures for a natural, sophisticated look.",
    image: "/products/mosaic/fc-301.png",
    gallery: ["/products/mosaic/fc-301.png"],
    hue: "Beige",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Kitchen Countertop", "Bathroom Vanity", "Lobby"],
    features: ["Non-porous", "Durable", "Seamless"],
    industries: ["residential", "hospitality", "commercial"],
    faqs: defaultFaqs,
  },
  {
    slug: "pebblon-tr-pista",
    name: "Pebblon TR. Pista",
    sku: "FC-302",
    category: "mosaic",
    description: "Soft pista green with translucent pebble accents.",
    longDescription: "Pebblon TR. Pista combines a soft pista green base with translucent pebble accents for a refreshing, luminous surface.",
    image: "/products/mosaic/fc-302.png",
    gallery: ["/products/mosaic/fc-302.png"],
    hue: "Green",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Bar Top", "Reception Desk", "Spa"],
    features: ["Translucent accents", "Non-porous", "Stain resistant"],
    industries: ["hospitality", "commercial", "residential"],
    faqs: defaultFaqs,
  },
  {
    slug: "pebblon-tr-white",
    name: "Pebblon TR. White",
    sku: "FC-303",
    category: "mosaic",
    description: "Crisp white with translucent pebble patterns.",
    longDescription: "Pebblon TR. White offers a crisp, clean white base with beautiful translucent pebble patterns that glow when backlit.",
    image: "/products/mosaic/fc-303.png",
    gallery: ["/products/mosaic/fc-303.png"],
    hue: "White",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Backlit Wall", "Kitchen Countertop", "Healthcare"],
    features: ["Translucent", "Hygienic", "Seamless"],
    industries: ["residential", "healthcare", "hospitality"],
    faqs: defaultFaqs,
  },
  {
    slug: "pebblon-tr-brown",
    name: "Pebblon TR. Brown",
    sku: "FC-304",
    category: "mosaic",
    description: "Warm brown with earthy translucent pebble textures.",
    longDescription: "Pebblon TR. Brown features warm, earthy tones with translucent pebble textures for a cozy yet modern feel.",
    image: "/products/mosaic/fc-304.png",
    gallery: ["/products/mosaic/fc-304.png"],
    hue: "Brown",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Reception Desk", "Restaurant Bar", "Office"],
    features: ["Translucent accents", "Durable", "Thermoformable"],
    industries: ["commercial", "hospitality", "corporate"],
    faqs: defaultFaqs,
  },
  {
    slug: "pebblon-grey",
    name: "Pebblon Grey",
    sku: "FC-305",
    category: "mosaic",
    description: "Modern grey with natural pebble-inspired depth.",
    longDescription: "Pebblon Grey offers a sleek, modern grey base with natural pebble-inspired depth for contemporary architectural spaces.",
    image: "/products/mosaic/fc-305.png",
    gallery: ["/products/mosaic/fc-305.png"],
    hue: "Grey",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Office Desk", "Retail Counter", "Hospitality"],
    features: ["Non-porous", "Impact resistant", "Seamless joints"],
    industries: ["corporate", "commercial", "hospitality"],
    faqs: defaultFaqs,
  },
  {
    slug: "pebblon-light-biscut",
    name: "Pebblon Light Biscut",
    sku: "FC-306",
    category: "mosaic",
    description: "Soft biscuit tone with subtle pebble detailing.",
    longDescription: "Pebblon Light Biscut features a soft, inviting biscuit tone with subtle pebble detailing for a warm interior aesthetic.",
    image: "/products/mosaic/fc-306.png",
    gallery: ["/products/mosaic/fc-306.png"],
    hue: "Beige",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Residential Kitchen", "Vanity", "Lobby"],
    features: ["Easy to clean", "Non-porous", "Seamless"],
    industries: ["residential", "hospitality", "commercial"],
    faqs: defaultFaqs,
  },
  {
    slug: "mystery-white",
    name: "Mystery White",
    sku: "FC-307",
    category: "mosaic",
    description: "Enigmatic white with fine mosaic grain.",
    longDescription: "Mystery White offers a subtle yet enigmatic look with its fine mosaic grain and pure white base.",
    image: "/products/mosaic/fc-307.png",
    gallery: ["/products/mosaic/fc-307.png"],
    hue: "White",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Hospitality", "Healthcare", "Residential"],
    features: ["Hygienic", "Low maintenance", "Seamless"],
    industries: ["healthcare", "hospitality", "residential"],
    faqs: defaultFaqs,
  },
  {
    slug: "navajo-white",
    name: "Navajo White",
    sku: "FC-308",
    category: "mosaic",
    description: "Creamy Navajo white with a delicate mosaic texture.",
    longDescription: "Navajo White provides a warm, creamy aesthetic with a delicate mosaic texture, ideal for traditional and modern homes alike.",
    image: "/products/mosaic/fc-308.png",
    gallery: ["/products/mosaic/fc-308.png"],
    hue: "Beige",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Kitchen", "Bathroom", "Living Space"],
    features: ["Stain resistant", "Non-porous", "Seamless joints"],
    industries: ["residential", "hospitality", "commercial"],
    faqs: defaultFaqs,
  },
  {
    slug: "ice-mosaic",
    name: "Ice Mosaic",
    sku: "FC-309",
    category: "mosaic",
    description: "Cool ice-inspired mosaic pattern with light depth.",
    longDescription: "Ice Mosaic captures the cool, crystalline look of ice with a modern mosaic pattern and subtle depth.",
    image: "/products/mosaic/fc-309.png",
    gallery: ["/products/mosaic/fc-309.png"],
    hue: "White",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Bar Top", "Countertop", "Feature Wall"],
    features: ["Light-reactive", "Non-porous", "Durable"],
    industries: ["hospitality", "commercial", "residential"],
    faqs: defaultFaqs,
  },
  {
    slug: "latle-mosiac",
    name: "Latle Mosiac",
    sku: "FC-310",
    category: "mosaic",
    description: "Rich latte-inspired mosaic with warm tones.",
    longDescription: "Latle Mosiac features rich latte-inspired tones in a sophisticated mosaic pattern, perfect for creating cozy, elegant spaces.",
    image: "/products/mosaic/fc-310.png",
    gallery: ["/products/mosaic/fc-310.png"],
    hue: "Brown",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Cafe", "Kitchen", "Reception"],
    features: ["Non-porous", "Stain resistant", "Seamless"],
    industries: ["hospitality", "residential", "commercial"],
    faqs: defaultFaqs,
  },
  {
    slug: "iron-ore-mosaic",
    name: "Iron Ore Mosaic",
    sku: "FC-311",
    category: "mosaic",
    description: "Strong iron ore-inspired mosaic with industrial appeal.",
    longDescription: "Iron Ore Mosaic brings a strong, industrial appeal to interiors with its deep metallic tones and rugged mosaic texture.",
    image: "/products/mosaic/fc-311.png",
    gallery: ["/products/mosaic/fc-311.png"],
    hue: "Grey",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Corporate Office", "Industrial Loft", "Bar"],
    features: ["Durable", "Non-porous", "Impact resistant"],
    industries: ["corporate", "commercial", "hospitality"],
    faqs: defaultFaqs,
  },
  {
    slug: "misty-pebble-grey",
    name: "Misty Pebble Grey",
    sku: "FC-312",
    category: "mosaic",
    description: "Soft grey with misty pebble-inspired patterns.",
    longDescription: "Misty Pebble Grey features a soft grey base with delicate, misty pebble patterns for a calm, serene atmosphere.",
    image: "/products/mosaic/fc-312.png",
    gallery: ["/products/mosaic/fc-312.png"],
    hue: "Grey",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Spa", "Bathroom", "Wellness Center"],
    features: ["Non-porous", "Hygienic", "Seamless"],
    industries: ["hospitality", "healthcare", "residential"],
    faqs: defaultFaqs,
  },
  {
    slug: "aurora-flakes-white",
    name: "Aurora Flakes White",
    sku: "FC-313",
    category: "mosaic",
    description: "Luminous white with shimmering aurora flakes.",
    longDescription: "Aurora Flakes White combines a luminous white base with shimmering flakes that evoke the beauty of the aurora borealis.",
    image: "/products/mosaic/fc-313.png",
    gallery: ["/products/mosaic/fc-313.png"],
    hue: "White",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Feature Wall", "Reception", "Luxury Kitchen"],
    features: ["Shimmering effect", "Non-porous", "Thermoformable"],
    industries: ["hospitality", "residential", "corporate"],
    faqs: defaultFaqs,
  },
  {
    slug: "black-galaxy-flake",
    name: "Black Galaxy Flake",
    sku: "FC-314",
    category: "mosaic",
    description: "Deep black with cosmic galaxy-inspired flakes.",
    longDescription: "Black Galaxy Flake features a deep black base with sparkling cosmic flakes for a bold, high-contrast statement.",
    image: "/products/mosaic/fc-314.png",
    gallery: ["/products/mosaic/fc-314.png"],
    hue: "Black",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Bar", "Nightclub", "Feature Wall"],
    features: ["Light-reactive", "Durable", "Stain resistant"],
    industries: ["hospitality", "commercial", "entertainment"],
    faqs: defaultFaqs,
  },
  {
    slug: "soft-stone-sprinkle",
    name: "Soft Stone Sprinkle",
    sku: "FC-315",
    category: "mosaic",
    description: "Gentle stone-inspired sprinkle pattern.",
    longDescription: "Soft Stone Sprinkle offers a gentle, natural look with its fine stone-inspired sprinkle pattern and neutral base.",
    image: "/products/mosaic/fc-315.png",
    gallery: ["/products/mosaic/fc-315.png"],
    hue: "Grey",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Countertop", "Vanity", "Office"],
    features: ["Non-porous", "Easy to maintain", "Seamless joints"],
    industries: ["residential", "corporate", "hospitality"],
    faqs: defaultFaqs,
  },
  {
    slug: "silver-spark-mist",
    name: "Silver Spark Mist",
    sku: "FC-316",
    category: "mosaic",
    description: "Cool mist with subtle silver sparkling accents.",
    longDescription: "Silver Spark Mist combines a cool, misty base with subtle silver sparks that catch the light beautifully.",
    image: "/products/mosaic/fc-316.png",
    gallery: ["/products/mosaic/fc-316.png"],
    hue: "Grey",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Reception Desk", "Bathroom", "Retail"],
    features: ["Light-reactive", "Non-porous", "Seamless"],
    industries: ["commercial", "hospitality", "residential"],
    faqs: defaultFaqs,
  },
  {
    slug: "fog-sprinkle",
    name: "Fog Sprinkle",
    sku: "FC-317",
    category: "mosaic",
    description: "Muted fog tone with fine sprinkle detailing.",
    longDescription: "Fog Sprinkle features a muted, atmospheric fog tone with fine sprinkle detailing for a sophisticated, understated look.",
    image: "/products/mosaic/fc-317.png",
    gallery: ["/products/mosaic/fc-317.png"],
    hue: "Grey",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Modern Kitchen", "Office", "Commercial Space"],
    features: ["Durable", "Non-porous", "Stain resistant"],
    industries: ["residential", "corporate", "commercial"],
    faqs: defaultFaqs,
  },
  {
    slug: "arctic-mist",
    name: "Arctic Mist",
    sku: "FC-318",
    category: "mosaic",
    description: "Cool arctic mist with a delicate mosaic texture.",
    longDescription: "Arctic Mist captures the cool essence of the arctic with a delicate mosaic texture and soft light-reflecting properties.",
    image: "/products/mosaic/fc-318.png",
    gallery: ["/products/mosaic/fc-318.png"],
    hue: "White",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Bathroom", "Spa", "Lobby"],
    features: ["Non-porous", "Hygienic", "Seamless joints"],
    industries: ["hospitality", "residential", "healthcare"],
    faqs: defaultFaqs,
  },
  {
    slug: "moon-gold-pebble",
    name: "Moon Gold Pebble",
    sku: "FC-319",
    category: "mosaic",
    description: "Celestial gold and moon-inspired pebble pattern.",
    longDescription: "Moon Gold Pebble features celestial gold and lunar-inspired tones in a mesmerizing pebble pattern.",
    image: "/products/mosaic/fc-319.png",
    gallery: ["/products/mosaic/fc-319.png"],
    hue: "Beige",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Feature Wall", "Bar", "Luxury Suite"],
    features: ["Shimmering accents", "Non-porous", "Durable"],
    industries: ["hospitality", "residential", "commercial"],
    faqs: defaultFaqs,
  },
  {
    slug: "granite-mist",
    name: "Granite Mist",
    sku: "FC-320",
    category: "mosaic",
    description: "Granite-inspired mist with natural stone depth.",
    longDescription: "Granite Mist combines the strength and look of granite with a soft, misty finish and natural stone depth.",
    image: "/products/mosaic/fc-320.png",
    gallery: ["/products/mosaic/fc-320.png"],
    hue: "Grey",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Heavy-duty Countertop", "Reception", "Retail"],
    features: ["Impact resistant", "Non-porous", "Seamless"],
    industries: ["commercial", "corporate", "hospitality"],
    faqs: defaultFaqs,
  },
  {
    slug: "polar-pebble",
    name: "Polar Pebble",
    sku: "FC-321",
    category: "mosaic",
    description: "Bright polar white with contrasting pebble patterns.",
    longDescription: "Polar Pebble features a bright, icy white base with contrasting pebble patterns for a crisp, high-impact surface.",
    image: "/products/mosaic/fc-321.png",
    gallery: ["/products/mosaic/fc-321.png"],
    hue: "White",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Kitchen", "Bathroom", "Healthcare"],
    features: ["Hygienic", "Non-porous", "Stain resistant"],
    industries: ["residential", "healthcare", "hospitality"],
    faqs: defaultFaqs,
  },
  {
    slug: "crystal-white-mosaic",
    name: "Crystal White",
    sku: "FC-601",
    category: "mosaic",
    description: "Pure crystal white with fine mosaic grain.",
    longDescription: "Crystal White offers a pure, crystalline appearance with a fine mosaic grain for ultimate brightness.",
    image: "/products/mosaic/fc-601.png",
    gallery: ["/products/mosaic/fc-601.png"],
    hue: "White",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Healthcare", "Kitchen", "Vanity"],
    features: ["Hygienic", "Non-porous", "Seamless"],
    industries: ["healthcare", "residential", "hospitality"],
    faqs: defaultFaqs,
  },
  {
    slug: "moonlight-glitter",
    name: "Moonlight Glitter",
    sku: "FC-602",
    category: "mosaic",
    description: "Soft moonlight with shimmering glitter particles.",
    longDescription: "Moonlight Glitter features a soft, celestial base with shimmering particles that glitter like a moonlit night.",
    image: "/products/mosaic/fc-602.png",
    gallery: ["/products/mosaic/fc-602.png"],
    hue: "Grey",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Feature Wall", "Bar", "Luxury Retail"],
    features: ["Glitter effect", "Non-porous", "Thermoformable"],
    industries: ["hospitality", "commercial", "residential"],
    faqs: defaultFaqs,
  },
  {
    slug: "driftstone-texture",
    name: "Driftstone Texture",
    sku: "FC-603",
    category: "mosaic",
    description: "Natural driftstone-inspired mosaic texture.",
    longDescription: "Driftstone Texture captures the rugged, natural beauty of wind-swept stone in a modern mosaic format.",
    image: "/products/mosaic/fc-603.png",
    gallery: ["/products/mosaic/fc-603.png"],
    hue: "Beige",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Outdoor Space", "Lobby", "Wall Cladding"],
    features: ["Textured surface", "Durable", "Weather resistant"],
    industries: ["commercial", "hospitality", "residential"],
    faqs: defaultFaqs,
  },
  {
    slug: "silver-creek-pattern",
    name: "Silver Creek Pattern",
    sku: "FC-604",
    category: "mosaic",
    description: "Flowing silver creek mosaic pattern.",
    longDescription: "Silver Creek Pattern features flowing, stream-inspired lines in a sophisticated silver mosaic palette.",
    image: "/products/mosaic/fc-604.png",
    gallery: ["/products/mosaic/fc-604.png"],
    hue: "Grey",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Reception Desk", "Feature Wall", "Furniture"],
    features: ["Flowing pattern", "Non-porous", "Seamless joints"],
    industries: ["corporate", "commercial", "hospitality"],
    faqs: defaultFaqs,
  },
  {
    slug: "fogline-texture",
    name: "Fogline Texture",
    sku: "FC-605",
    category: "mosaic",
    description: "Misty fogline mosaic with linear texture.",
    longDescription: "Fogline Texture offers a misty, linear aesthetic with a subtle mosaic texture that adds depth to vertical surfaces.",
    image: "/products/mosaic/fc-605.png",
    gallery: ["/products/mosaic/fc-605.png"],
    hue: "Grey",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Wall Panel", "Office", "Hospitality"],
    features: ["Linear texture", "Non-porous", "Durable"],
    industries: ["corporate", "commercial", "hospitality"],
    faqs: defaultFaqs,
  },
  {
    slug: "natural-earthline",
    name: "Natural Earthline",
    sku: "FC-606",
    category: "mosaic",
    description: "Earthy natural line pattern in mosaic finish.",
    longDescription: "Natural Earthline combines earthy, grounded tones with a sophisticated line pattern in a durable mosaic finish.",
    image: "/products/mosaic/fc-606.png",
    gallery: ["/products/mosaic/fc-606.png"],
    hue: "Brown",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Kitchen", "Residential", "Public Space"],
    features: ["Natural aesthetic", "Non-porous", "Seamless"],
    industries: ["residential", "commercial", "hospitality"],
    faqs: defaultFaqs,
  },
  {
    slug: "pure-white",
    name: "Pure White",
    sku: "FC-101",
    category: "plain",
    description: "Classic pure white solid surface for a clean, minimalist look.",
    longDescription: "Pure White offers a timeless, bright white finish that provides a perfect canvas for any architectural design.",
    image: "/products/plain-surface/fc-101.png",
    gallery: ["/products/plain-surface/fc-101.png"],
    hue: "White",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Kitchen Countertop", "Bathroom Vanity", "Healthcare"],
    features: ["Non-porous", "Hygienic", "Seamless"],
    industries: ["residential", "healthcare", "commercial"],
    faqs: defaultFaqs,
  },
  {
    slug: "super-white",
    name: "Super White",
    sku: "FC-102",
    category: "plain",
    description: "Ultra-bright white surface with exceptional clarity.",
    longDescription: "Super White is engineered for maximum brightness and clarity, ideal for spaces that require a pristine, high-impact aesthetic.",
    image: "/products/plain-surface/fc-102.png",
    gallery: ["/products/plain-surface/fc-102.png"],
    hue: "White",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Modern Kitchen", "Reception", "Retail"],
    features: ["Ultra-bright", "Stain resistant", "Durable"],
    industries: ["residential", "commercial", "hospitality"],
    faqs: defaultFaqs,
  },
  {
    slug: "sapphire-grey",
    name: "Sapphire Grey",
    sku: "FC-103",
    category: "plain",
    description: "Elegant sapphire grey with a smooth, matte finish.",
    longDescription: "Sapphire Grey brings a sophisticated, cool-toned grey to your interiors, perfect for contemporary and professional settings.",
    image: "/products/plain-surface/fc-103.png",
    gallery: ["/products/plain-surface/fc-103.png"],
    hue: "Grey",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Office Desk", "Countertop", "Wall Panel"],
    features: ["Smooth texture", "Impact resistant", "Seamless joints"],
    industries: ["corporate", "commercial", "residential"],
    faqs: defaultFaqs,
  },
  {
    slug: "golden-brown",
    name: "Golden Brown",
    sku: "FC-104",
    category: "plain",
    description: "Warm golden brown for an inviting interior feel.",
    longDescription: "Golden Brown combines earthy warmth with a professional finish, creating spaces that feel both luxurious and welcoming.",
    image: "/products/plain-surface/fc-104.png",
    gallery: ["/products/plain-surface/fc-104.png"],
    hue: "Brown",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Restaurant Bar", "Kitchen", "Furniture"],
    features: ["Warm tones", "Non-porous", "Thermoformable"],
    industries: ["hospitality", "residential", "commercial"],
    faqs: defaultFaqs,
  },
  {
    slug: "ivory-plain",
    name: "Ivory",
    sku: "FC-105",
    category: "plain",
    description: "Classic ivory tone for timeless elegance.",
    longDescription: "Ivory provides a soft, warm alternative to pure white, maintaining a clean look with a touch of traditional luxury.",
    image: "/products/plain-surface/fc-105.png",
    gallery: ["/products/plain-surface/fc-105.png"],
    hue: "Beige",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Bathroom", "Kitchen", "Lobby"],
    features: ["Timeless color", "Easy to clean", "Seamless"],
    industries: ["residential", "hospitality", "commercial"],
    faqs: defaultFaqs,
  },
  {
    slug: "emeraid-green",
    name: "Emeraid Green",
    sku: "FC-106",
    category: "plain",
    description: "Vibrant emerald green for bold design statements.",
    longDescription: "Emeraid Green offers a striking, saturated green hue that serves as a centerpiece in any modern design project.",
    image: "/products/plain-surface/fc-106.png",
    gallery: ["/products/plain-surface/fc-106.png"],
    hue: "Green",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Feature Wall", "Furniture", "Retail Display"],
    features: ["Vibrant color", "Durable", "Non-porous"],
    industries: ["commercial", "hospitality", "residential"],
    faqs: defaultFaqs,
  },
  {
    slug: "sand-stone-plain",
    name: "Sand Stone",
    sku: "FC-107",
    category: "plain",
    description: "Natural sand stone tone for grounded interiors.",
    longDescription: "Sand Stone brings the calm, neutral essence of the desert into your space with its smooth, durable finish.",
    image: "/products/plain-surface/fc-107.png",
    gallery: ["/products/plain-surface/fc-107.png"],
    hue: "Beige",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Countertop", "Vanity", "Public Space"],
    features: ["Neutral palette", "Stain resistant", "Seamless"],
    industries: ["commercial", "residential", "hospitality"],
    faqs: defaultFaqs,
  },
  {
    slug: "crimson-red",
    name: "Crimson Red",
    sku: "FC-108",
    category: "plain",
    description: "Deep, passionate crimson red for high-energy spaces.",
    longDescription: "Crimson Red is a bold, energetic choice for brands and homeowners who want to make an unforgettable impression.",
    image: "/products/plain-surface/fc-108.png",
    gallery: ["/products/plain-surface/fc-108.png"],
    hue: "Red",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Bar", "Restaurant", "Statement Kitchen"],
    features: ["High contrast", "Durable", "Impact resistant"],
    industries: ["hospitality", "commercial", "residential"],
    faqs: defaultFaqs,
  },
  {
    slug: "black-plain",
    name: "Black",
    sku: "FC-109",
    category: "plain",
    description: "Pure, deep black for ultimate sophistication.",
    longDescription: "Black offers a sleek, modern, and high-contrast finish that defines luxury and professional quality.",
    image: "/products/plain-surface/fc-109.png",
    gallery: ["/products/plain-surface/fc-109.png"],
    hue: "Black",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Executive Office", "Luxury Kitchen", "Bar"],
    features: ["Sleek finish", "Non-porous", "Seamless joints"],
    industries: ["corporate", "residential", "hospitality"],
    faqs: defaultFaqs,
  },
  {
    slug: "leon-yellow",
    name: "Leon Yellow",
    sku: "FC-110",
    category: "plain",
    description: "Bright, sunny yellow to illuminate any project.",
    longDescription: "Leon Yellow brings a burst of energy and light, perfect for creative offices, play areas, or bold kitchen designs.",
    image: "/products/plain-surface/fc-110.png",
    gallery: ["/products/plain-surface/fc-110.png"],
    hue: "Yellow",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Office", "Play Area", "Kitchen Accents"],
    features: ["Bright color", "Durable", "Easy maintenance"],
    industries: ["corporate", "commercial", "residential"],
    faqs: defaultFaqs,
  },
  {
    slug: "blue-ocean",
    name: "Blue Ocean",
    sku: "FC-111",
    category: "plain",
    description: "Calm and deep ocean blue solid surface.",
    longDescription: "Blue Ocean captures the serenity of the sea, providing a tranquil and stable atmosphere for wellness and luxury spaces.",
    image: "/products/plain-surface/fc-111.png",
    gallery: ["/products/plain-surface/fc-111.png"],
    hue: "Blue",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Spa", "Bathroom", "Feature Wall"],
    features: ["Water resistant", "Non-porous", "Seamless"],
    industries: ["hospitality", "residential", "healthcare"],
    faqs: defaultFaqs,
  },
  {
    slug: "cream-plain",
    name: "Cream",
    sku: "FC-112",
    category: "plain",
    description: "Rich cream tone for a soft and luxurious finish.",
    longDescription: "Cream offers a versatile, warm neutral that pairs beautifully with natural wood and metallic accents.",
    image: "/products/plain-surface/fc-112.png",
    gallery: ["/products/plain-surface/fc-112.png"],
    hue: "Beige",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Kitchen", "Vanity", "Lobby"],
    features: ["Soft aesthetic", "Easy to clean", "Non-porous"],
    industries: ["residential", "hospitality", "commercial"],
    faqs: defaultFaqs,
  },
  {
    slug: "pista-plain",
    name: "Pista",
    sku: "FC-113",
    category: "plain",
    description: "Soft pista green for a fresh and modern look.",
    longDescription: "Pista provides a refreshing, light green hue that adds a touch of nature-inspired color to modern interiors.",
    image: "/products/plain-surface/fc-113.png",
    gallery: ["/products/plain-surface/fc-113.png"],
    hue: "Green",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Healthcare", "Kitchen", "Office"],
    features: ["Fresh color", "Hygienic", "Seamless joints"],
    industries: ["healthcare", "residential", "corporate"],
    faqs: defaultFaqs,
  },
  {
    slug: "frost-grey",
    name: "Frost Grey",
    sku: "FC-114",
    category: "plain",
    description: "Cool frost grey for a sleek, industrial aesthetic.",
    longDescription: "Frost Grey is a sophisticated choice for industrial lofts and modern corporate offices, offering a clean and durable surface.",
    image: "/products/plain-surface/fc-114.png",
    gallery: ["/products/plain-surface/fc-114.png"],
    hue: "Grey",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Worktop", "Reception", "Wall Cladding"],
    features: ["Cool tones", "Non-porous", "Durable"],
    industries: ["corporate", "commercial", "residential"],
    faqs: defaultFaqs,
  },
  {
    slug: "light-gray-plain",
    name: "Light Gray",
    sku: "FC-115",
    category: "plain",
    description: "Versatile light gray for all-purpose design.",
    longDescription: "Light Gray is the perfect balanced neutral, suitable for any application from residential kitchens to commercial airports.",
    image: "/products/plain-surface/fc-115.png",
    gallery: ["/products/plain-surface/fc-115.png"],
    hue: "Grey",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Floor", "Wall", "Countertop"],
    features: ["Durable", "Non-porous", "Seamless"],
    industries: ["commercial", "residential", "healthcare"],
    faqs: defaultFaqs,
  },
  {
    slug: "glacier-blue",
    name: "Glacier Blue",
    sku: "FC-116",
    category: "plain",
    description: "Crisp glacier blue for a clean and refreshing feel.",
    longDescription: "Glacier Blue brings a cool, professional touch to interiors, making it ideal for healthcare and modern retail spaces.",
    image: "/products/plain-surface/fc-116.png",
    gallery: ["/products/plain-surface/fc-116.png"],
    hue: "Blue",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Healthcare", "Bathroom", "Retail Display"],
    features: ["Hygienic", "Non-porous", "Impact resistant"],
    industries: ["healthcare", "commercial", "hospitality"],
    faqs: defaultFaqs,
  },
  {
    slug: "baby-pink",
    name: "Baby Pink",
    sku: "FC-117",
    category: "plain",
    description: "Soft baby pink for a gentle and playful aesthetic.",
    longDescription: "Baby Pink offers a soft, comforting hue perfect for children's spaces, boutiques, or creative interior accents.",
    image: "/products/plain-surface/fc-117.png",
    gallery: ["/products/plain-surface/fc-117.png"],
    hue: "Pink",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Boutique", "Childcare", "Feature Wall"],
    features: ["Soft color", "Durable", "Non-porous"],
    industries: ["commercial", "residential", "hospitality"],
    faqs: defaultFaqs,
  },
  {
    slug: "warm-sand",
    name: "Warm Sand",
    sku: "FC-118",
    category: "plain",
    description: "Cozy warm sand tone for natural interior designs.",
    longDescription: "Warm Sand brings a grounded, organic feel to spaces, working well with natural materials like wood and stone.",
    image: "/products/plain-surface/fc-118.png",
    gallery: ["/products/plain-surface/fc-118.png"],
    hue: "Beige",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Kitchen", "Lobby", "Furniture"],
    features: ["Natural tones", "Seamless", "Non-porous"],
    industries: ["residential", "hospitality", "commercial"],
    faqs: defaultFaqs,
  },
  {
    slug: "purple-plain",
    name: "Purple",
    sku: "FC-119",
    category: "plain",
    description: "Rich purple for a luxurious and creative touch.",
    longDescription: "Purple is a bold choice for high-end hospitality and retail environments where creativity and luxury are paramount.",
    image: "/products/plain-surface/fc-119.png",
    gallery: ["/products/plain-surface/fc-119.png"],
    hue: "Purple",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Bar Top", "Feature Wall", "Display"],
    features: ["Rich color", "Thermoformable", "Durable"],
    industries: ["hospitality", "commercial", "entertainment"],
    faqs: defaultFaqs,
  },
  {
    slug: "red-plain",
    name: "Red",
    sku: "FC-120",
    category: "plain",
    description: "Classic vibrant red for high-impact designs.",
    longDescription: "Red is the ultimate statement color, providing energy and passion to restaurants, showrooms, and modern kitchens.",
    image: "/products/plain-surface/fc-120.png",
    gallery: ["/products/plain-surface/fc-120.png"],
    hue: "Red",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Restaurant", "Exhibition", "Kitchen"],
    features: ["Vibrant", "Non-porous", "Seamless joints"],
    industries: ["commercial", "hospitality", "residential"],
    faqs: defaultFaqs,
  },
  {
    slug: "ford-blue",
    name: "Ford Blue",
    sku: "FC-121",
    category: "plain",
    description: "Strong, industrial Ford Blue for reliable surfaces.",
    longDescription: "Ford Blue is a powerful, saturated blue that brings a sense of reliability and strength to corporate and commercial spaces.",
    image: "/products/plain-surface/fc-121.png",
    gallery: ["/products/plain-surface/fc-121.png"],
    hue: "Blue",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Office", "Retail Display", "Workshop"],
    features: ["Strong color", "Impact resistant", "Non-porous"],
    industries: ["corporate", "commercial", "industrial"],
    faqs: defaultFaqs,
  },
  {
    slug: "chocolate-brown",
    name: "Chocolate Brown",
    sku: "FC-122",
    category: "plain",
    description: "Deep chocolate brown for a rich and earthy aesthetic.",
    longDescription: "Chocolate Brown offers a grounded, sophisticated look that pairs excellently with warm lighting and luxury furniture.",
    image: "/products/plain-surface/fc-122.png",
    gallery: ["/products/plain-surface/fc-122.png"],
    hue: "Brown",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Luxury Bar", "Kitchen", "Office Desk"],
    features: ["Earthy finish", "Durable", "Seamless"],
    industries: ["hospitality", "residential", "corporate"],
    faqs: defaultFaqs,
  },
  {
    slug: "slate-gray-plain",
    name: "Slate Gray",
    sku: "FC-123",
    category: "plain",
    description: "Deep slate gray for a professional and modern look.",
    longDescription: "Slate Gray provides a serious and professional aesthetic, ideal for high-traffic commercial and corporate environments.",
    image: "/products/plain-surface/fc-123.png",
    gallery: ["/products/plain-surface/fc-123.png"],
    hue: "Grey",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Reception", "Public Restroom", "Commercial Space"],
    features: ["Non-porous", "Stain resistant", "Durable"],
    industries: ["commercial", "corporate", "healthcare"],
    faqs: defaultFaqs,
  },
  {
    slug: "pumpkin-orange",
    name: "Pumpkin Orange",
    sku: "FC-124",
    category: "plain",
    description: "Energetic pumpkin orange for creative environments.",
    longDescription: "Pumpkin Orange is a vibrant and creative choice, perfect for modern offices, cafes, and bold residential accents.",
    image: "/products/plain-surface/fc-124.png",
    gallery: ["/products/plain-surface/fc-124.png"],
    hue: "Orange",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Cafe", "Office Accent", "Furniture"],
    features: ["Vibrant color", "Seamless", "Non-porous"],
    industries: ["hospitality", "corporate", "residential"],
    faqs: defaultFaqs,
  },
  {
    slug: "nile-blue",
    name: "Nile Blue",
    sku: "FC-125",
    category: "plain",
    description: "Deep Nile blue for a serene and stable look.",
    longDescription: "Nile Blue captures the depth and calm of water, providing a professional yet soothing aesthetic for high-end projects.",
    image: "/products/plain-surface/fc-125.png",
    gallery: ["/products/plain-surface/fc-125.png"],
    hue: "Blue",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Feature Wall", "Spa", "Lobby"],
    features: ["Deep color", "Non-porous", "Impact resistant"],
    industries: ["hospitality", "commercial", "residential"],
    faqs: defaultFaqs,
  },
  {
    slug: "olive-green-plain",
    name: "Olive Green",
    sku: "FC-126",
    category: "plain",
    description: "Muted olive green for organic and sophisticated designs.",
    longDescription: "Olive Green brings an organic, sophisticated touch to interiors, perfect for modern eco-inspired architectural projects.",
    image: "/products/plain-surface/fc-126.png",
    gallery: ["/products/plain-surface/fc-126.png"],
    hue: "Green",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Countertop", "Furniture", "Eco-Design"],
    features: ["Natural aesthetic", "Durable", "Non-porous"],
    industries: ["residential", "hospitality", "corporate"],
    faqs: defaultFaqs,
  },
  {
    slug: "dolphin-gray",
    name: "Dolphin Gray",
    sku: "FC-127",
    category: "plain",
    description: "Balanced dolphin gray for a soft and modern finish.",
    longDescription: "Dolphin Gray is a versatile mid-tone grey that provides a soft, professional look for any interior surface.",
    image: "/products/plain-surface/fc-127.png",
    gallery: ["/products/plain-surface/fc-127.png"],
    hue: "Grey",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Office", "Kitchen", "Public Space"],
    features: ["Smooth finish", "Non-porous", "Seamless joints"],
    industries: ["corporate", "residential", "commercial"],
    faqs: defaultFaqs,
  },
  {
    slug: "shamrock-green",
    name: "Shamrock Green",
    sku: "FC-128",
    category: "plain",
    description: "Lucky shamrock green for a fresh and bright look.",
    longDescription: "Shamrock Green is a vibrant, natural green that brings energy and life to retail and hospitality environments.",
    image: "/products/plain-surface/fc-128.png",
    gallery: ["/products/plain-surface/fc-128.png"],
    hue: "Green",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Retail", "Cafe", "Play Area"],
    features: ["Bright color", "Non-porous", "Durable"],
    industries: ["commercial", "hospitality", "residential"],
    faqs: defaultFaqs,
  },
  {
    slug: "beige-brown",
    name: "Beige Brown",
    sku: "FC-129",
    category: "plain",
    description: "Balanced beige brown for warm, grounded interiors.",
    longDescription: "Beige Brown offers a harmonious blend of warm tones, creating spaces that are both comfortable and professional.",
    image: "/products/plain-surface/fc-129.png",
    gallery: ["/products/plain-surface/fc-129.png"],
    hue: "Beige",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Lobby", "Residential Kitchen", "Vanity"],
    features: ["Warm neutral", "Stain resistant", "Seamless"],
    industries: ["hospitality", "residential", "commercial"],
    faqs: defaultFaqs,
  },
  {
    slug: "parrot-green",
    name: "Parrot Green",
    sku: "FC-130",
    category: "plain",
    description: "Exotic parrot green for vibrant and creative spaces.",
    longDescription: "Parrot Green is an exotic, high-energy hue perfect for highlighting creative zones and modern retail displays.",
    image: "/products/plain-surface/fc-130.png",
    gallery: ["/products/plain-surface/fc-130.png"],
    hue: "Green",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Retail Display", "Creative Studio", "Cafe"],
    features: ["Vibrant hue", "Durable", "Non-porous"],
    industries: ["commercial", "hospitality", "corporate"],
    faqs: defaultFaqs,
  },
  {
    slug: "silver-mist-plain",
    name: "Silver Mist",
    sku: "FC-131",
    category: "plain",
    description: "Elegant silver mist for a clean, metallic-like aesthetic.",
    longDescription: "Silver Mist provides a sophisticated, light grey finish with a unique clarity that mimics high-end metallic surfaces.",
    image: "/products/plain-surface/fc-131.png",
    gallery: ["/products/plain-surface/fc-131.png"],
    hue: "Grey",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Modern Kitchen", "Reception", "Bathroom"],
    features: ["Light reflecting", "Non-porous", "Seamless joints"],
    industries: ["residential", "commercial", "hospitality"],
    faqs: defaultFaqs,
  },
  {
    slug: "deep-cocoa",
    name: "Deep Cocoa",
    sku: "FC-132",
    category: "plain",
    description: "Rich deep cocoa for a warm and premium feel.",
    longDescription: "Deep Cocoa offers a luxurious, earthy brown that adds weight and premium quality to architectural interiors.",
    image: "/products/plain-surface/fc-132.png",
    gallery: ["/products/plain-surface/fc-132.png"],
    hue: "Brown",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Executive Desk", "Luxury Bar", "Kitchen"],
    features: ["Rich tones", "Impact resistant", "Durable"],
    industries: ["corporate", "hospitality", "residential"],
    faqs: defaultFaqs,
  },
  {
    slug: "moon-whisper",
    name: "Moon Whisper",
    sku: "FC-133",
    category: "plain",
    description: "Soft moon whisper grey for tranquil environments.",
    longDescription: "Moon Whisper is a delicate, pale grey that creates a sense of peace and modern cleanliness in any space.",
    image: "/products/plain-surface/fc-133.png",
    gallery: ["/products/plain-surface/fc-133.png"],
    hue: "Grey",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Spa", "Wellness Center", "Bedroom"],
    features: ["Soothing color", "Non-porous", "Hygienic"],
    industries: ["hospitality", "healthcare", "residential"],
    faqs: defaultFaqs,
  },
  {
    slug: "classic-cement",
    name: "Classic Cement",
    sku: "FC-134",
    category: "plain",
    description: "Industrial classic cement for modern minimalist design.",
    longDescription: "Classic Cement captures the raw, industrial look of concrete in a durable, non-porous solid surface finish.",
    image: "/products/plain-surface/fc-134.png",
    gallery: ["/products/plain-surface/fc-134.png"],
    hue: "Grey",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Modern Kitchen", "Worktop", "Floor Panel"],
    features: ["Raw aesthetic", "Easy maintenance", "Seamless"],
    industries: ["residential", "corporate", "commercial"],
    faqs: defaultFaqs,
  },
  {
    slug: "rustic-mustard",
    name: "Rustic Mustard",
    sku: "FC-135",
    category: "plain",
    description: "Deep rustic mustard for warm and characterful spaces.",
    longDescription: "Rustic Mustard brings a unique, grounded warmth to interiors, perfect for artisanal cafes and boutique designs.",
    image: "/products/plain-surface/fc-135.png",
    gallery: ["/products/plain-surface/fc-135.png"],
    hue: "Yellow",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Cafe", "Boutique", "Residential Accent"],
    features: ["Warm rustic tone", "Durable", "Non-porous"],
    industries: ["hospitality", "commercial", "residential"],
    faqs: defaultFaqs,
  },
  {
    slug: "black-mist-cascade",
    name: "Black Mist Cascade",
    sku: "FC-715",
    category: "alabaster",
    description: "Deep black with cascading mist patterns.",
    longDescription: "Black Mist Cascade features a deep black base with cascading mist patterns for a bold, dramatic surface.",
    image: "/products/alabaster/fc-715.png",
    gallery: ["/products/alabaster/fc-715.png"],
    hue: "Black",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Reception", "Bar", "Feature Wall"],
    features: ["Non-porous", "Stain resistant", "Anti-bacterial"],
    industries: ["commercial", "corporate", "hospitality"],
    faqs: defaultFaqs,
  },
  {
    slug: "marine-mist-texture",
    name: "Marine Mist Texture",
    sku: "FC-716",
    category: "alabaster",
    description: "Marine-inspired mist with textured patterns.",
    longDescription: "Marine Mist Texture brings ocean-inspired textures with soft marine mist patterns for serene interiors.",
    image: "/products/alabaster/fc-716.png",
    gallery: ["/products/alabaster/fc-716.png"],
    hue: "Blue",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Spa", "Bathroom", "Hospitality"],
    features: ["Non-porous", "Waterproof", "Hygienic"],
    industries: ["hospitality", "residential", "healthcare"],
    faqs: defaultFaqs,
  },
  {
    slug: "marine-mist-texture-ii",
    name: "Marine Mist Texture II",
    sku: "FC-717",
    category: "alabaster",
    description: "Enhanced marine mist with refined texture patterns.",
    longDescription: "Marine Mist Texture II is an enhanced version with refined marine textures and deeper tonal variations.",
    image: "/products/alabaster/fc-717.png",
    gallery: ["/products/alabaster/fc-717.png"],
    hue: "Blue",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Spa", "Pool", "Bathroom"],
    features: ["Non-porous", "Waterproof", "Seamless"],
    industries: ["hospitality", "residential", "healthcare"],
    faqs: defaultFaqs,
  },
  {
    slug: "amber-net-texture",
    name: "Amber Net Texture",
    sku: "FC-718",
    category: "alabaster",
    description: "Amber tones with delicate net-like texture.",
    longDescription: "Amber Net Texture features warm amber tones with a delicate net-like texture pattern for refined spaces.",
    image: "/products/alabaster/fc-718.png",
    gallery: ["/products/alabaster/fc-718.png"],
    hue: "Beige",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Countertop", "Feature Wall", "Retail"],
    features: ["Non-porous", "Stain resistant", "Thermoformable"],
    industries: ["residential", "commercial", "hospitality"],
    faqs: defaultFaqs,
  },
  {
    slug: "sunlit-pearl-drift",
    name: "Sunlit Pearl Drift",
    sku: "FC-719",
    category: "alabaster",
    description: "Sunlit pearl tones with gentle drift patterns.",
    longDescription: "Sunlit Pearl Drift captures the glow of sunlit pearls with gentle drifting patterns for luminous interiors.",
    image: "/products/alabaster/fc-719.png",
    gallery: ["/products/alabaster/fc-719.png"],
    hue: "White",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Vanity", "Bathroom", "Hospitality"],
    features: ["Non-porous", "Hygienic", "Seamless"],
    industries: ["residential", "hospitality", "healthcare"],
    faqs: defaultFaqs,
  },
  {
    slug: "desert-woodgrain",
    name: "Desert Woodgrain",
    sku: "FC-720",
    category: "alabaster",
    description: "Desert-inspired wood grain surface.",
    longDescription: "Desert Woodgrain brings the warmth of desert landscapes with natural wood grain aesthetics in a solid surface.",
    image: "/products/alabaster/fc-720.png",
    gallery: ["/products/alabaster/fc-720.png"],
    hue: "Beige",
    region: "Middle East",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Kitchen", "Furniture", "Commercial"],
    features: ["Warm tone", "Non-porous", "Repairable"],
    industries: ["residential", "commercial", "hospitality"],
    faqs: defaultFaqs,
  },
  {
    slug: "cream-breeze-flow",
    name: "Cream Breeze Flow",
    sku: "FC-721",
    category: "alabaster",
    description: "Creamy tones with gentle breeze-like flow patterns.",
    longDescription: "Cream Breeze Flow features creamy tones with gentle, breeze-like flow patterns for light, airy interiors.",
    image: "/products/alabaster/fc-721.png",
    gallery: ["/products/alabaster/fc-721.png"],
    hue: "White",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Kitchen", "Bathroom", "Healthcare"],
    features: ["Non-porous", "Hygienic", "Seamless"],
    industries: ["residential", "healthcare", "hospitality"],
    faqs: defaultFaqs,
  },
  {
    slug: "lime-wave-texture",
    name: "Lime Wave Texture",
    sku: "FC-722",
    category: "alabaster",
    description: "Fresh lime tones with wave-like texture.",
    longDescription: "Lime Wave Texture features fresh lime tones with wave-like texture patterns for vibrant, modern spaces.",
    image: "/products/alabaster/fc-722.png",
    gallery: ["/products/alabaster/fc-722.png"],
    hue: "Green",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Retail", "Spa", "Feature Wall"],
    features: ["Non-porous", "Thermoformable", "Stain resistant"],
    industries: ["hospitality", "commercial", "residential"],
    faqs: defaultFaqs,
  },
  {
    slug: "ocean-softwave",
    name: "Ocean Softwave",
    sku: "FC-723",
    category: "alabaster",
    description: "Soft ocean-inspired wave patterns.",
    longDescription: "Ocean Softwave brings calming ocean-inspired wave patterns in soft tones for tranquil interior spaces.",
    image: "/products/alabaster/fc-723.png",
    gallery: ["/products/alabaster/fc-723.png"],
    hue: "Blue",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Spa", "Bathroom", "Hospitality"],
    features: ["Non-porous", "Waterproof", "Hygienic"],
    industries: ["hospitality", "residential", "healthcare"],
    faqs: defaultFaqs,
  },
  {
    slug: "citrine-thunder-flow",
    name: "Citrine Thunder Flow",
    sku: "FC-724",
    category: "alabaster",
    description: "Citrine tones with dramatic thunder flow patterns.",
    longDescription: "Citrine Thunder Flow combines vibrant citrine tones with dramatic thunder-inspired flow patterns.",
    image: "/products/alabaster/fc-724.png",
    gallery: ["/products/alabaster/fc-724.png"],
    hue: "Beige",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Feature Wall", "Reception", "Bar Top"],
    features: ["Non-porous", "Stain resistant", "Thermoformable"],
    industries: ["hospitality", "commercial", "corporate"],
    faqs: defaultFaqs,
  },
  {
    slug: "golden-storm-fusion",
    name: "Golden Storm Fusion",
    sku: "FC-725",
    category: "alabaster",
    description: "Golden tones with stormy fusion patterns.",
    longDescription: "Golden Storm Fusion fuses golden tones with dramatic storm-inspired patterns for luxurious interiors.",
    image: "/products/alabaster/fc-725.png",
    gallery: ["/products/alabaster/fc-725.png"],
    hue: "Beige",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Reception", "Bar", "Feature Wall"],
    features: ["Non-porous", "Seamless", "Thermoformable"],
    industries: ["hospitality", "commercial", "corporate"],
    faqs: defaultFaqs,
  },
  {
    slug: "graphite-cascade",
    name: "Graphite Cascade",
    sku: "FC-726",
    category: "alabaster",
    description: "Graphite tones with cascading patterns.",
    longDescription: "Graphite Cascade features deep graphite tones with cascading patterns for modern, sophisticated spaces.",
    image: "/products/alabaster/fc-726.png",
    gallery: ["/products/alabaster/fc-726.png"],
    hue: "Black",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Reception", "Bar Top", "Feature Wall"],
    features: ["Non-porous", "Anti-bacterial", "Stain resistant"],
    industries: ["commercial", "corporate", "hospitality"],
    faqs: defaultFaqs,
  },
  {
    slug: "rustic-timber-stripes",
    name: "Rustic Timber Stripes",
    sku: "FC-727",
    category: "alabaster",
    description: "Rustic timber-inspired stripe patterns.",
    longDescription: "Rustic Timber Stripes captures the natural beauty of timber with rustic stripe patterns in a solid surface.",
    image: "/products/alabaster/fc-727.png",
    gallery: ["/products/alabaster/fc-727.png"],
    hue: "Beige",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Kitchen", "Furniture", "Commercial"],
    features: ["Non-porous", "Hygienic", "Repairable"],
    industries: ["residential", "commercial", "hospitality"],
    faqs: defaultFaqs,
  },
  {
    slug: "bronze-forest-veins",
    name: "Bronze Forest Veins",
    sku: "FC-728",
    category: "alabaster",
    description: "Bronze tones with forest-inspired vein patterns.",
    longDescription: "Bronze Forest Veins combines bronze tones with forest-inspired vein patterns for warm, natural interiors.",
    image: "/products/alabaster/fc-728.png",
    gallery: ["/products/alabaster/fc-728.png"],
    hue: "Beige",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Countertop", "Feature Wall", "Retail"],
    features: ["Non-porous", "Thermoformable", "Seamless"],
    industries: ["residential", "commercial", "hospitality"],
    faqs: defaultFaqs,
  },

  {
    slug: "copper-vein",
    name: "Copper Vein",
    sku: "FC-MO-112",
    category: "mosaic",
    description: "Copper-toned metallic mosaic pattern.",
    longDescription:
      "Copper Vein brings warm metallic copper tones through a mosaic-inspired pattern perfect for high-end commercial installations.",
    image: "https://images.unsplash.com/photo-1496395035753-7da72844d0b2?auto=format&fit=crop&w=1600&q=80",
    gallery: ["https://images.unsplash.com/photo-1496395035753-7da72844d0b2?auto=format&fit=crop&w=1600&q=80"],
    hue: "Orange",
    region: "Global",
    thickness: "12mm",
    dimensions: "3000 x 760 mm",
    applications: ["Bar Top", "Reception", "Feature Wall"],
    features: ["Metallic finish", "Seamless"],
    industries: ["hospitality", "commercial", "corporate"],
    specSheetUrl: "/specs/copper-vein.pdf",
    faqs: defaultFaqs,
  },
]

export function getProduct(slug: string) {
  return products.find((p) => p.slug === slug)
}

export function getRelatedProducts(slug: string, category: ProductCategory, limit = 4) {
  return products.filter((p) => p.slug !== slug && p.category === category).slice(0, limit)
}
